AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - spec/**/*
    - Gemfile

Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: false
